music/urls.py
from . import views
from django.urls import path
from django.conf.urls import url

app_name = 'music'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:album_id>/', views.detail, name='detail'),
]

music/models.py
from django.db import models


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album


# Create your views here.
def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums,}
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album</title>
</head>
<body>
<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>
<img src="{{album.album_logo}}">
<ul>
    {% for song in album.song_set.all %}
    <li>{{song.song_title}} - {{song.file_type}} </li>
    {% endfor %}
</ul>
</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Albuns List</title>
</head>
<body>
<H1>Lista de Albuns:</H1>
{% if all_albums %}
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}"> {{ album.artist }} - {{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>Não há albuns para exibir</h3>
{% endif %}
</body>
</html>